apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmcharts.operb.example.io
spec:
  group: operb.example.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                chart:
                  type: string
                chartVersion:
                  type: string
                values:
                  type: string
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
      # subresources for the custom resource
      subresources:
        # enables the status subresource
        status: {}
  names:
    kind: HelmChart
    plural: helmcharts
    singular: helmchart
  scope: Namespaced
